%sql
SELECT
     clnt_obj_id,
     clnt_obj_id_r,
     yr_cd,
     yr_cd_r,
     mnth_seq_nbr,
     mnth_seq_nbr_r,
     qtr_seq_nbr,
     qtr_seq_nbr_r,
     job_cd,
     job_cd_r,
     hr_orgn_id,
     hr_orgn_id_r,
     work_cntry_cd,
     work_cntry_cd_r,
     work_state_cd,
     work_state_cd_r,
     work_loc_cd,
     work_loc_cd_r,
     mngr_pers_obj_id,
     mngr_pers_obj_id_r,
     metrics.metric_ky,
     metrics.insight_reason,
     metrics.insight_score,
     metrics.insight_type,
     metrics.insight_events,
     CAST(metrics.insight_metrics[12] AS DOUBLE) AS percentile_rank,
     ins_empl_cnt,
     ins_empl_cnt_r,
     empl_count,
     empl_count_r,
     pctg_empl_count,
     pctg_empl_count_r,
     num_dimensions,
     CAST(metrics.insight_metrics[0] AS DOUBLE) AS metric_value,
     CAST(metrics.insight_metrics[1] AS DOUBLE) AS metric_value_r,
     CAST(metrics.insight_metrics[4] AS DOUBLE) AS diff,
     CAST(metrics.insight_metrics[5] AS DOUBLE) AS percentage_diff,
     CAST(metrics.insight_metrics[6] AS DOUBLE) AS normalised_diff,
     CAST(metrics.insight_metrics[7] AS DOUBLE) AS normalised_percentage_diff,
     CAST(metrics.insight_metrics[8] AS DOUBLE) AS zscore_diff,
     CAST(metrics.insight_metrics[9] AS DOUBLE) AS zscore_percentage_diff,
     CAST(metrics.insight_metrics[10] AS DOUBLE) AS normalised_zscore_diff,
     CAST(metrics.insight_metrics[11] AS DOUBLE) AS normalised_zscore_percentage_diff,
     CAST(metrics.insight_metrics[13] AS DOUBLE) AS min_metric_value,
     CAST(metrics.insight_metrics[14] AS DOUBLE) AS max_metric_value,
     CONCAT(
        "{ \"this\": ", COALESCE(CAST(metrics.insight_metrics[0] AS STRING),'null'),
         ",\"that\": ", COALESCE(CAST(metrics.insight_metrics[1] AS STRING),'null'),
         ",\"this_events\": ", COALESCE(CAST(metrics.insight_metrics[2] AS STRING),'null'),
         ",\"that_events\": ", COALESCE(CAST(metrics.insight_metrics[3] AS STRING),'null'),
         ",\"insight\": {\"diff\" : ", COALESCE(CAST(metrics.insight_metrics[4] AS STRING),'null'),
         ",\"percentage_diff\" : ", COALESCE(CAST(metrics.insight_metrics[5] AS STRING),'null'),
         ",\"normalised_diff\" : ", COALESCE(CAST(metrics.insight_metrics[6] AS STRING),'null'),
         ",\"normalised_percentage_diff\" : ", COALESCE(CAST(metrics.insight_metrics[7] AS STRING),'null'),
         ",\"ins_empl_cnt\" : ", COALESCE(CAST(ins_empl_cnt AS STRING),'null'),
         ",\"ins_empl_cnt_cmpr_with\" : ", COALESCE(CAST(ins_empl_cnt_r AS STRING),'null'),
         ",\"zscore_diff\" : ", COALESCE(CAST(metrics.insight_metrics[8] AS STRING),'null'),
         ",\"zscore_percentage_diff\" : ", COALESCE(CAST(metrics.insight_metrics[9] AS STRING),'null'),
         ",\"normalised_zscore_diff\" : ", COALESCE(CAST(metrics.insight_metrics[10] AS STRING),'null'),
         ",\"normalised_zscore_percentage_diff\" : ", COALESCE(CAST(metrics.insight_metrics[11] AS STRING),'null'),
         ",\"percentile_rank\" : ", COALESCE(CAST(metrics.insight_metrics[12] AS STRING),'null'),
         ",\"percentile_zscore\" : ", COALESCE(CAST(metrics.insight_metrics[15] AS STRING),'null'),
         ",\"percentile_normalised_zscore\" : ", COALESCE(CAST(metrics.insight_metrics[16] AS STRING),'null'),
         ",\"mean_diff\" : ", COALESCE(CAST(metrics.insight_metrics[17] AS STRING),'null'),
         ",\"stddev_diff\" : ", COALESCE(CAST(metrics.insight_metrics[18] AS STRING),'null'),
         ",\"mean_pctg_diff\" : ", COALESCE(CAST(metrics.insight_metrics[19] AS STRING),'null'),
         ",\"stddev_pctg_diff\" : ", COALESCE(CAST(metrics.insight_metrics[20] AS STRING),'null'),
         ",\"mean_norm_diff\" : ", COALESCE(CAST(metrics.insight_metrics[21] AS STRING),'null'),
         ",\"stddev_norm_diff\" : ", COALESCE(CAST(metrics.insight_metrics[22] AS STRING),'null'),
         ",\"mean_norm_pctg_diff\" : ", COALESCE(CAST(metrics.insight_metrics[23] AS STRING),'null'),
         ",\"stddev_norm_pctg_diff\" : ", COALESCE(CAST(metrics.insight_metrics[24] AS STRING),'null'),
         ",\"percentile_mean\" : ", COALESCE(CAST(metrics.insight_metrics[25] AS STRING),'null'),
         ",\"percentile_stddev\" : ", COALESCE(CAST(metrics.insight_metrics[26] AS STRING),'null'),
         ",\"percentile_norm_mean\" : ", COALESCE(CAST(metrics.insight_metrics[27] AS STRING),'null'),
         ",\"percentile_norm_stddev\" : ", COALESCE(CAST(metrics.insight_metrics[28] AS STRING),'null'), "}}"
     ) AS insights_json,
     2 AS dmn_ky,
    environment
     FROM(SELECT
          clnt_obj_id,
          clnt_obj_id_r,
          mnth_seq_nbr,
          mnth_seq_nbr_r,
          qtr_seq_nbr,
          qtr_seq_nbr_r,
          cast(yr_seq_nbr as int)     AS yr_cd,
          cast(yr_seq_nbr_r as int)   AS yr_cd_r,
          d_job_cd        AS job_cd,
          d_job_cd_r      AS job_cd_r,
          d_hr_orgn_id    AS hr_orgn_id,
         d_hr_orgn_id_r  AS hr_orgn_id_r,
          d_work_cntry_cd AS work_cntry_cd,
          d_work_cntry_cd_r AS work_cntry_cd_r,
          d_work_state_cd AS work_state_cd,
          d_work_state_cd_r AS work_state_cd_r,
          d_work_loc_cd   AS work_loc_cd,
          d_work_loc_cd_r AS work_loc_cd_r,
          mngr_pers_obj_id,
          mngr_pers_obj_id_r,
          insight_reason_turnover_rate,
          insight_score_turnover_rate,
          insight_type_turnover_rate,
          turnover_rate_metrics,
          turnover_rate_events,
          insight_reason_voln_turnover_rate,
          insight_score_voln_turnover_rate,
          insight_type_voln_turnover_rate,
          voln_turnover_rate_metrics,
          voln_turnover_rate_events,
          insight_reason_internal_mobility_rate,
          insight_score_internal_mobility_rate,
          insight_type_internal_mobility_rate,
          internal_mobility_rate_metrics,
          internal_mobility_rate_events,
          insight_reason_newhire_turnover_rate,
          insight_score_newhire_turnover_rate,
          insight_type_newhire_turnover_rate,
          newhire_turnover_rate_metrics,
          newhire_turnover_rate_events,
          insight_reason_average_tenure,
          insight_score_average_tenure,
          insight_type_average_tenure,
          average_tenure_metrics,
          average_tenure_events,
          insight_reason_avg_time_to_promotion,
          insight_score_avg_time_to_promotion,
          insight_type_avg_time_to_promotion,
          avg_time_to_promotion_metrics,
          avg_time_to_promotion_events,
          insight_reason_retention_rate,
          insight_score_retention_rate,
          insight_type_retention_rate,
          retention_rate_metrics,
          retention_rate_events,
          insight_reason_num_hires,
          insight_score_num_hires,
          insight_type_num_hires,
          num_hires_metrics,
          num_hires_events,
          insight_reason_num_terminations,
          insight_score_num_terminations,
          insight_type_num_terminations,
          num_terminations_metrics,
          num_terminations_events,
          insight_reason_headcount,
          insight_score_headcount,
          insight_type_headcount,
          headcount_metrics,
          headcount_events,
          insight_reason_leave_percentage,
          insight_score_leave_percentage,
         insight_type_leave_percentage,
          leave_percentage_metrics,
          leave_percentage_events,
          num_employees as ins_empl_cnt,
          num_employees_r as ins_empl_cnt_r,
          tot_rpt_headcount                   AS empl_count,
          tot_rpt_headcount_r                 AS empl_count_r,
          percentage_headcount        AS pctg_empl_count,
          percentage_headcount_r      AS pctg_empl_count_r,
          num_dimensions,
          environment
        FROM ${__BLUE_MAIN_DB__}.emi_ins_intl_bm_hr_waf_manager
        DISTRIBUTE BY clnt_obj_id
        --DISTRIBUTE BY CONCAT(COALESCE(yr_cd,''),COALESCE(qtr_seq_nbr,''),COALESCE(mnth_seq_nbr,''),COALESCE(job_cd,''),
       --COALESCE(hr_orgn_id,''),COALESCE(work_cntry_cd,''),COALESCE(work_state_cd,''),COALESCE(work_loc_cd,''))
        --WHERE environment='${environment}'
        ) hr
      LATERAL VIEW stack(11,  -- Total number of rows each row is exploded to
                            '76', insight_reason_turnover_rate,insight_score_turnover_rate,insight_type_turnover_rate,turnover_rate_metrics,turnover_rate_events,
                           --'52', insight_reason_female_percentage,insight_score_female_percentage,insight_type_female_percentage,female_percentage_metrics,
                            '53', insight_reason_voln_turnover_rate,insight_score_voln_turnover_rate,insight_type_voln_turnover_rate,voln_turnover_rate_metrics,voln_turnover_rate_events,
                            '65', insight_reason_internal_mobility_rate,insight_score_internal_mobility_rate,insight_type_internal_mobility_rate,internal_mobility_rate_metrics,internal_mobility_rate_events,
                            '69', insight_reason_newhire_turnover_rate,insight_score_newhire_turnover_rate,insight_type_newhire_turnover_rate,newhire_turnover_rate_metrics,newhire_turnover_rate_events,
                            '60', insight_reason_average_tenure,insight_score_average_tenure,insight_type_average_tenure,average_tenure_metrics,average_tenure_events,
                            --'68', insight_reason_span_of_control,insight_score_span_of_control,insight_type_span_of_control,span_of_control_metrics,
                            --'302', insight_reason_compa_ratio,insight_score_compa_ratio,insight_type_compa_ratio,compa_ratio_metrics,
                            '79', insight_reason_avg_time_to_promotion,insight_score_avg_time_to_promotion,insight_type_avg_time_to_promotion,avg_time_to_promotion_metrics,avg_time_to_promotion_events,
                            '78', insight_reason_retention_rate,insight_score_retention_rate,insight_type_retention_rate,retention_rate_metrics,retention_rate_events,
                            '74', insight_reason_num_hires,insight_score_num_hires,insight_type_num_hires,num_hires_metrics,num_hires_events,
                            '63', insight_reason_num_terminations,insight_score_num_terminations,insight_type_num_terminations,num_terminations_metrics,num_terminations_events,
                            --'51', insight_reason_inactive_headcount,insight_score_inactive_headcount,insight_type_inactive_headcount,inactive_headcount_metrics,
                            --'55', insight_reason_parttime_headcount,insight_score_parttime_headcount,insight_type_parttime_headcount,parttime_headcount_metrics,
                            --'56', insight_reason_temp_headcount,insight_score_temp_headcount,insight_type_temp_headcount,temp_headcount_metrics,
                             '57', insight_reason_headcount,insight_score_headcount,insight_type_headcount,headcount_metrics,headcount_events,
                            '59', insight_reason_leave_percentage,insight_score_leave_percentage,insight_type_leave_percentage,leave_percentage_metrics,leave_percentage_events
                          ) metrics AS metric_ky, insight_reason, insight_score, insight_type, insight_metrics, insight_events
